# Generated by Django 4.2.11 on 2026-06-24 19:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEnrichmentQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower number means higher priority')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of times this VIN has been retried for enrichment')),
                ('error_message', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['vin'], name='vehicles_ve_vin_498297_idx'), models.Index(fields=['status'], name='vehicles_ve_status_fb8651_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vin', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(17)])),
                ('plate_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('make', models.CharField(blank=True, max_length=50, null=True)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2100)])),
                ('trim', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(max_length=50)),
                ('chasis_number', models.CharField(max_length=50)),
                ('original_color', models.CharField(blank=True, max_length=30, null=True)),
                ('current_color', models.CharField(blank=True, max_length=30, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('is_stolen', models.BooleanField(default=False)),
                ('interpol_stolen_date', models.DateField(blank=True, null=True)),
                ('last_full_check', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['vin'], name='vehicles_ve_vin_d8dea1_idx'), models.Index(fields=['plate_number'], name='vehicles_ve_plate_n_a3accc_idx'), models.Index(fields=['make', 'model', 'year'], name='vehicles_ve_make_2e7e5d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnershipTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(blank=True, max_length=15)),
                ('registration_date', models.DateField()),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('FRSC', 'FRSC Records'), ('User_Upload', 'User Uploaded'), ('Dealer_Input', 'Dealer Input'), ('Customs', 'Customs Declaration')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_traces', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicles_ow_vehicle_5642ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='MileageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField()),
                ('mileage', models.IntegerField(help_text='Mileage in kilometers')),
                ('source', models.CharField(choices=[('Customs_Entry', 'Customs Declaration'), ('MOT_Center', 'MOT Inspection'), ('Insurance_Claim', 'Insurance Claim'), ('User_Input', 'User Uploaded'), ('Service_Record', 'Service Record')], max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_logs', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['vehicle'], name='vehicles_mi_vehicle_cd06bf_idx'), models.Index(fields=['recorded_at'], name='vehicles_mi_recorde_b06798_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_m_number', models.CharField(max_length=50, unique=True)),
                ('port_of_entry', models.CharField(choices=[('PTML', 'Port of Lagos'), ('Apapa', 'Apapa Port Lagos'), ('Tin Can', 'Tin Can Island Port Lagos'), ('Onne', 'Onne Port Rivers State'), ('Calabar', 'Calabar Port Cross River State'), ('Warri', 'Warri Port Delta State'), ('Port Harcourt', 'Port Harcourt Port Rivers State'), ('Kano', 'Kano Port Kano State'), ('Kaduna', 'Kaduna Port Kaduna State'), ('Abuja', 'Abuja Port FCT')], max_length=100)),
                ('date_of_import', models.DateField()),
                ('cif_value_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duty_paid_ngn', models.DecimalField(decimal_places=2, max_digits=15)),
                ('custom_agent_name', models.CharField(max_length=100)),
                ('custom_agent_contact', models.CharField(max_length=15)),
                ('first_owner_name', models.CharField(max_length=100)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_records', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['form_m_number'], name='vehicles_im_form_m__5a6c71_idx'), models.Index(fields=['vehicle'], name='vehicles_im_vehicle_a45df3_idx')],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('damage_type', models.CharField(choices=[('Flood', 'Flood Damage'), ('Fire', 'Fire Damage'), ('Collision', 'Collision'), ('Theft', 'Theft Recovery'), ('Structural', 'Structural Damage'), ('Hail', 'Hail Damage')], max_length=20)),
                ('source', models.CharField(choices=[('US_Export', 'US Export (Copart/IAAI)'), ('Local_Insurance', 'Local Insurance Claim'), ('FRSC', 'FRSC Inspection Report'), ('User_Report', 'User Reported'), ('Interpol', 'Interpol Stolen Vehicle Report')], max_length=20)),
                ('severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Salvage', 'Salvage'), ('Total_Loss', 'Total Loss')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reported_date', models.DateField()),
                ('source_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='vehicles.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['vehicle'], name='vehicles_da_vehicle_715dba_idx')],
            },
        ),
    ]
